/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HelloWorld {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ReactWrapper {
        "message": string;
    }
}
declare global {
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLReactWrapperElement extends Components.ReactWrapper, HTMLStencilElement {
    }
    var HTMLReactWrapperElement: {
        prototype: HTMLReactWrapperElement;
        new (): HTMLReactWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "hello-world": HTMLHelloWorldElement;
        "my-component": HTMLMyComponentElement;
        "react-wrapper": HTMLReactWrapperElement;
    }
}
declare namespace LocalJSX {
    interface HelloWorld {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ReactWrapper {
        "message"?: string;
    }
    interface IntrinsicElements {
        "hello-world": HelloWorld;
        "my-component": MyComponent;
        "react-wrapper": ReactWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hello-world": LocalJSX.HelloWorld & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "react-wrapper": LocalJSX.ReactWrapper & JSXBase.HTMLAttributes<HTMLReactWrapperElement>;
        }
    }
}
